"""empty message

Revision ID: 08cee51cc6d7
Revises: d5113f740390
Create Date: 2021-07-13 17:22:43.740465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cee51cc6d7'
down_revision = 'd5113f740390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('phone', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'phone')
    # ### end Alembic commands ###
