"""empty message

Revision ID: c28ae5812dd4
Revises: c419e301487a
Create Date: 2021-05-27 21:07:11.088769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28ae5812dd4'
down_revision = 'c419e301487a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('currentURL', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'currentURL')
    # ### end Alembic commands ###
