"""empty message

Revision ID: c3ba15e8f8e6
Revises: c28ae5812dd4
Create Date: 2021-06-03 17:47:19.589441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ba15e8f8e6'
down_revision = 'c28ae5812dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secretid', sa.Integer(), nullable=False),
    sa.Column('chatid', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('su', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['secretid'], ['secrets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('secrets')
    # ### end Alembic commands ###
