"""empty message

Revision ID: c419e301487a
Revises: 
Create Date: 2021-04-29 00:54:12.095211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c419e301487a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('mail', sa.String(length=140), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('postmsg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postmsg',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True),
    sa.Column('mail', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True),
    sa.Column('body', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('messages')
    # ### end Alembic commands ###
