"""empty message

Revision ID: d5113f740390
Revises: e89222a3d085
Create Date: 2021-06-22 16:09:32.732367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5113f740390'
down_revision = 'e89222a3d085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fs_uniquifier', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'user', ['fs_uniquifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'fs_uniquifier')
    # ### end Alembic commands ###
