"""initial migration

Revision ID: ea148b4b4ee5
Revises: 
Create Date: 2024-11-22 00:29:33.194829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea148b4b4ee5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messageid', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('chapter', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['messageid'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secretid', sa.Integer(), nullable=False),
    sa.Column('chatid', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('su', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['secretid'], ['secrets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatid')
    )
    op.create_table('roles_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currentURL', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('unread', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('unread')
        batch_op.drop_column('phone')
        batch_op.drop_column('currentURL')

    op.drop_table('roles_users')
    op.drop_table('members')
    op.drop_table('history')
    op.drop_table('user')
    op.drop_table('secrets')
    op.drop_table('role')
    # ### end Alembic commands ###
